### ISSUE TITLE
Implémenter une feature votes

### ISSUE THREAD

**Issue by colasbd** [nuitdebout/nuitdebout.github.io#31]
À mon avis c'est hyper important !

L'AG ajoute des propositions soumises au vote (à titre indicatif) sur la page web.
Les votes ne seraient pris qu'à titre indicatif.

Ça va faire exploser le traffic ;-)

**Comment by tomplays** [comment]
@colasbd cf : https://www.loomio.org/d/mfg8A0kU/test-des-outils-edemocratie-pour-mise-en-place-urgente#_=_

**Comment by colasbd** [comment]
Ok, cool et intéressant.
