### ISSUE TITLE
Généraliser les domaines ville

### ISSUE THREAD

**Issue by devingfx** [nuitdebout/nuitdebout.github.io#33]
Bonjour, le but du site est de fédérer je penses!

Il y'a peu à faire pour en faire un portail des villes!

Voici ma proposition:
- Changer le sous-domaine de l'actuel site pour: paris.nuitdebout.fr
- Faire de www.nuitdebout.fr un portail commun avec seulement dans l'ordre: 
  - Carte des villes (à mettre à jour!! de nouvelles villes ce sont lancées), qui contienent un  lien vers les sous-domaines de la ville, libre à chaque ville de faire un fork du github.
  - Le mouvement, infos, 
  - Participer
  - Wiki commun >> Y mettre le même Logo NUITDebout celui du site

Qu'en pensez-vous?

**Comment by pyg77** [comment]
:-1: 
Je me mèle peut être de ce qui ne me regarde pas (et j'ai peut être mal compris ta proposition), mais en tant que militant "anti-centralisation" (d'internet), je ne suis pas certain que ce soit une bonne idée: il suffirait en effet d'une décision de fermer le domaine nuitdebout.fr pour briser l'élan (numérique).
Soit c'est un mouvement autogéré, soit c'est un mouvement centralisé :)

Par contre, que "lyon.nuitdebout.fr" renvoie vers nuitdeboutlyon.fr est simple, ne coute rien, et évite la centralisation.
Idem, pas de souci avec ta proposition que le site actuel pointe vers paris.nuitdebout.fr

Pour la carte, pas de souci (NB : je dois ouvrir une issue sur framacarte/umap pour que soit rajouté la possibilité de sortir des flux RSS de la carte. Le dev principal a peu de temps, donc soit quelqu'un s'y colle, soit il faudra attendre un peu)

Pour le reste, pas de problème. (bon, sur le fork du github, je suis là encore pour que chaque ville s'autogère en fonction de ses ressources/besoins, mais c'est moins critique que pour le NDD)

**Comment by devingfx** [comment]
Je suis tout à fait d'accord avec ton annalyse de de la centralisation! Je ne parlais que de faire pointer les CNAME vers les hébergements respectifs des villes... 
Il lest par contre important, pour la communication et la cenralisation d'info, de pouvoir donner un lien général. Quitte à le changer si le domaine se retrouve fermé! Il est important de décentralisé l'hébergement sous-jacent par contre!

**Comment by devingfx** [comment]
Au niveau de la carte: Je ne connais pas bien framecarte, mais par contre j'ai été dev 4ans chez Orange pour la page maps.orange.fr. Je connais bien les outis cartographiques nottament leaflet (libre) et open street maps.
Il est possible de faire une carte dynamique, affichant des marqueurs issus des infos entrée dans un wiki github.... via un service backend en nodejs...

**Comment by tomplays** [comment]
@devingfx @pyg77 je vous invite a regarder ce qui se dit sur le chat.nuitdebout.fr (dont chan #nuitdebout.fr) et les discut. sur loomio.les points que vous soulevez sont soit en cours de dev soit débattus

**Comment by alexsegura** [comment]
J'aurais tendance à dire qu'on peut fermer cette issue. 
Depuis 700ead31fc9d512578edba091030ef1251aa99ba il y a non pas des sous-domaines ville, mais des pages ville, ce qui revient un peu au même, et ça fonctionne tant qu'on est sous du Gihub Pages. 

Pour le moment, si une ville a un site propre, l'idée est de faire une iframe ou une redirection. 
Les fichiers `index.html` pour chaque ville ont été générés automatiquement, mais on peut les modifier quand même, la génération automatique c'était pour avoir une base.

**Comment by devingfx** [comment]
Comment on fait pour modif la page relatif à sa ville dans github et rajouter une redirection?
On peut passer par le site ou il faut faire un pull request?

**Comment by alexsegura** [comment]
Faut faire une PR stp.
