### ISSUE TITLE
Proposer sur le site une palette d'outils numériques pour s'organiser au sein de chaque rassemblement

### ISSUE THREAD

**Issue by SimonSarazin** [nuitdebout/nuitdebout.github.io#5]
Ce serait super d'avoir une rubrique avec les outils pour s'organiser au sein de chaque rassemblement

Pierre de Indiehosters propose de déployer un service libre de chat pour toutes les nuit debout (basé sur Rocket.chat, voir démo ici : https://chat.indie.host/, sur le principe de slack mais en libre.) et un service de gestionnaire de tâches (voir démo ici https://wekan.indie.host (c'est un trello like, en libre aussi). 
Il est possible aussi de déployer un mediawiki (avec l'éditeur visue) pour gérer les contenus basé (comme on l'a fait ici pour un autre projet assemblee.encommuns.org). Cela aiderait chaque groupe à partager ses contenus, comptes rendus, etc...

On pourrait juste rediriger le nom de domain chat.nuitdebout.fr, tableau.nuitdebout.fr, wiki.nuitdebout.fr pour avoir ces 3 services à proposer gratuitement et libres. Après, libre à chaque groupe de les utiliser ou pas.

On peut aussi proposer loomio.org pour tout ce qui est prise de décision (outil libre qui est né lors des occupy)

Un serveur de liste de discussion où facilement créer sa liste serait génial aussi pour récupérer tous les mails. Il est possible de faire une demande à ce sujet à Framasoft.

Où se font les échanges sur l'outillage numérique pour les nuit debout ?

PS : voir proposition de Pierre ici : https://github.com/indiehosters/nice-hosting-providers/issues/8#

**Comment by johangirod** [comment]
Hey, ça me semble une excellente idée. On est justement en train de discuter des outils numériques pour le futur du mouvement. Pour l'instant on est sur un groupe telegram, mais le but serait de passer sur un rocket.chat au plus vite ! 

Dès que tu es inscrit je t'ajoute au groupe !

**Comment by stragu** [comment]
Très bonnes idées, merci de promouvoir les solutions libres, je pense que c'est très important. Ravi de voir que la carte des Nuits Debout sur le site utilise Framacarte et OSM aussi.
De la même manière, est-ce vous pensez que l'on pourrait conseiller des outils de communication libres et sécurisés afin d'encourager les participants à se protéger ? Par exemple, recommander l'usage de Signal/Kontalk/Tox pour communiquer avec des amis, de Diaspora pour réseau-socialiser, de Tor pour naviguer, de GPG pour chiffrer des emails...

**Comment by pyg77** [comment]
Pour les raisons évoquées ici http://linuxfr.org/users/nemolivier/journaux/besoin-de-competences-numeriques-a-la-nuitdebout#comment-1651475 Framasoft ne peut pas faire un soutien direct à NuitDebout.
Cependant, une association, c'est aussi et surtout des individus, donc NuitDebout peut toujours nous contacter https://contact.framasoft.org on essaiera toujours de répondre de notre mieux aux questions.

Par ailleurs, même si on discute d'outils, je rejoins @stragu sur le fait qu'il s'agit avant tout d'avoir de bonnes pratiques plutôt que de bons outils : quels protocoles de communications pour quels usages ? Quels niveaux de chiffrement ? Quelles responsabilités ? Quelle maîtrise des plateformes et des données ?

Bref, on (association Framasoft) est ouvert à la discussion et au partage d'expérience :) 
Et pas impossible que certains d'entre nous soient prêt à filer un coup de main bénévoles en dehors de l'asso ;)

Ha, et j'oubliais : indiehosters peut être un partenaire de confiance pour NuitDebout (coucou Pierre) :)

**Comment by SimonSarazin** [comment]
Je crois que le mouvement déploie tout un tas d'outils donc on peut fermer cette issue :-) 
A découvrir ici : https://wiki.nuitdebout.fr/wiki/Num%C3%A9rique
Youhou :-) !
