### ISSUE TITLE
Proposition d'architecture basée sur un CDN

### ISSUE THREAD

**Issue by wimpheling** [nuitdebout/nuitdebout.github.io#6]
Le problème du site par rapport à l'hébergement est que selon l'actualité on risque de faire face à de grosses pointes de trafic.

J'ai une proposition d'architecture pour pallier durablement à ça :
- On héberge le site en statique (sur github pages par exemple)
- Au lieu de proposer les flux FB et twitter comme on le fait actuellement (le serveur récupère les infos chez FB et twitter pour chaque personne qui se connecte), on met sur notre serveur un daemon qui va récupérer les flux toutes les minutes.
- Le JSON récupéré est alors commité dans un fichier sur le github ( un fichier statique api/facebook.json ). Vu qu'on héberge chez github la MAJ est automatique.

Avantages :
- On a un hébergement ultra fiable à coût 0
- Le serveur n'a pas à être rendu public, donc il est à l'abri des attaques

Inconvénients
- Le flux n'est mis à jour qu'une fois par minute (ca ne me parait pas très grave)
- La 3me API utilisée est Bambuser, je ne me suis pas penché dessus donc je ne sais pas si le système marche avec ce site (est ce qu'il genere un token unique à chaque fois ?)

**Comment by johangirod** [comment]
Ca me semble une solution pas mal, qui a le mérite de répondre au problème rapidement. Par contre, c'est un peu sale :) 
On va se retrouver avec masse de commit trash qui vont pourrir l'historique très rapidement.

Perso je suis plus pour une solution standard, avec static front sur github et une api back sur un serveur à nous. En rajoutant du cache sur les appels api (soit sous forme de fichier json, soit http), et en rassemblant les trois requetes en une seule on peut économiser pas mal de traffic, et supporter la charge.

**Comment by fadomire** [comment]
a priori on part sur static sur githubpage et api sur serveur dédé
