### ISSUE TITLE
Duplicate SEO content

### ISSUE THREAD

**Issue by Oza94** [nuitdebout/nuitdebout.github.io#75]
Bonjour,

Le même contenu disponible à plusieurs NDD différent fait baisser le score SEO pour Google. Aujourd'hui il y a : 
- nuitdebout.fr
- nuitdebout.github.io

Il serait bon de garder nuitdebout.fr en site institutionnel, et nuitdebout.github.io pourrait servir de page d'information pour les devs' qu'en pensez vous?

**Comment by tomplays** [comment]
helllo,
gogle ne semble pas indexer : https://www.google.fr/#safe=off&q=nuitdebout.github.io 
parce que cette url est redigée vers nuitdebout.fr (pour qq heures encore c'est qui qui "heberge" le site

il n'y a donc qu'une seule url

**Comment by Oza94** [comment]
Au temps pour moi, je suis allé trop vite en besogne !
